// Generated by view binder compiler. Do not edit!
package com.example.truegg.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.ImageView;
import android.widget.RelativeLayout;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.example.truegg.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ActivityDetailsBinding implements ViewBinding {
  @NonNull
  private final RelativeLayout rootView;

  @NonNull
  public final Button HomeButton;

  @NonNull
  public final TextView calories;

  @NonNull
  public final TextView caloriesText;

  @NonNull
  public final TextView dateText;

  @NonNull
  public final ImageView image;

  @NonNull
  public final TextView name;

  private ActivityDetailsBinding(@NonNull RelativeLayout rootView, @NonNull Button HomeButton,
      @NonNull TextView calories, @NonNull TextView caloriesText, @NonNull TextView dateText,
      @NonNull ImageView image, @NonNull TextView name) {
    this.rootView = rootView;
    this.HomeButton = HomeButton;
    this.calories = calories;
    this.caloriesText = caloriesText;
    this.dateText = dateText;
    this.image = image;
    this.name = name;
  }

  @Override
  @NonNull
  public RelativeLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityDetailsBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityDetailsBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_details, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityDetailsBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.HomeButton;
      Button HomeButton = ViewBindings.findChildViewById(rootView, id);
      if (HomeButton == null) {
        break missingId;
      }

      id = R.id.calories;
      TextView calories = ViewBindings.findChildViewById(rootView, id);
      if (calories == null) {
        break missingId;
      }

      id = R.id.caloriesText;
      TextView caloriesText = ViewBindings.findChildViewById(rootView, id);
      if (caloriesText == null) {
        break missingId;
      }

      id = R.id.dateText;
      TextView dateText = ViewBindings.findChildViewById(rootView, id);
      if (dateText == null) {
        break missingId;
      }

      id = R.id.image;
      ImageView image = ViewBindings.findChildViewById(rootView, id);
      if (image == null) {
        break missingId;
      }

      id = R.id.name;
      TextView name = ViewBindings.findChildViewById(rootView, id);
      if (name == null) {
        break missingId;
      }

      return new ActivityDetailsBinding((RelativeLayout) rootView, HomeButton, calories,
          caloriesText, dateText, image, name);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
